version: "2.2"
services:
  db:
    container_name: reviews-db
    build: ./db/
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
  server:
    container_name: reviews-server
    build: ./server/
    restart: always
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis://cache
      DATABASE_URL: postgres://postgres:postgres@reviews-db:5432/reviews
      NODE_ENV: development
    ports:
      - "3000:3000"
  fec:
    container_name: fec
    build: ./FEC/
    restart: always
    depends_on:
      - server
    environment:
      NODE_ENV: development
    ports:
      - "8000:8000"
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
    ports:
      - "6379:6379"
volumes:
  postgres-volume: